# Use a small, optimized base image
FROM node:20-alpine

ENV NODE_ENV=production
ENV APP_PORT=3000

WORKDIR /app

COPY package*.json ./

RUN npm install --only=production

COPY . .

EXPOSE 3001

CMD ["node", "src/index.js"]