apiVersion: apps/v1
kind: Deployment
metadata:
  name: apps-db
  namespace: job-portal
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apps-db
  template:
    metadata:
      labels:
        app: apps-db
    spec:
      containers:
        - name: apps-db
          image: postgres:16-alpine
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: "apps_db"
            - name: POSTGRES_USER
              value: "jp_user"
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: job-portal-secrets
                  key: DB_PASSWORD