apiVersion: apps/v1
kind: Deployment
metadata:
  name: jobs-db
  namespace: job-portal
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jobs-db
  template:
    metadata:
      labels:
        app: jobs-db
    spec:
      containers:
        - name: jobs-db
          image: postgres:16-alpine
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: "jobs_db"
            - name: POSTGRES_USER
              value: "jp_user"
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: job-portal-secrets
                  key: DB_PASSWORD
          volumeMounts:
            - name: schema
              mountPath: /docker-entrypoint-initdb.d
            - name: data
              mountPath: /var/lib/postgresql/data
          readinessProbe:
            exec:
              command: ["pg_isready", "-U", "jp_user", "-d", "jobs_db"]
            initialDelaySeconds: 10
            periodSeconds: 5
      volumes:
        - name: schema
          configMap:
            name: jobs-db-schema
        - name: data
          persistentVolumeClaim:
            claimName: jobs-db-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jobs-db-pvc
  namespace: job-portal
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: jobs-db
  namespace: job-portal
spec:
  selector:
    app: jobs-db
  ports:
    - port: 5432
      targetPort: 5432