FROM nginx:alpine

COPY nginx.conf /etc/nginx/nginx.conf

COPY webapp/ /usr/share/nginx/html/

EXPOSE 80

HEALTHCHECK --interval=30s --timeout=5s \
  CMD wget -qO- http://localhost/index.html || exit 1
