name: job-portal

services:

  users-db:
    image: postgres:16-alpine
    container_name: jp-users-db
    environment:
      POSTGRES_DB:       users_db
      POSTGRES_USER:     jp_user
      POSTGRES_PASSWORD: jp_pass
    ports:
      - "5433:5432"
    volumes:
      - users-db-data:/var/lib/postgresql/data
      - ./User Management Service/init-scripts:/docker-entrypoint-initdb.d:ro
    networks:
      - job-portal-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U jp_user -d users_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  user-management-service:
    build:
      context: ./User Management Service
      dockerfile: dockerfile
    container_name: jp-user-service
    ports:
      - "3001:3001"
    env_file:
      - ./User Management Service/.env
    networks:
      - job-portal-net
    depends_on:
      users-db:
        condition: service_healthy
    restart: unless-stopped

networks:
  job-portal-net:
    name: job-portal-net
    driver: bridge

volumes:
  users-db-data:
    name: jp-users-db-data