services:
  # --- USER SERVICE stack ---
  user-db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: user_admin
      POSTGRES_PASSWORD: user_password
      POSTGRES_DB: user_db
    ports:
      - "5431:5432"

  user-service:
    build: ./User\ Management\ Service
    ports:
      - "3001:3000"
    depends_on:
      - user-db
    environment:
      DATABASE_URL: postgres://user_admin:user_password@user-db:5432/user_db

  # --- JOB SERVICE stack ---
  job-db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: job_admin
      POSTGRES_PASSWORD: job_password
      POSTGRES_DB: job_db
    ports:
      - "5432:5432"

  job-service:
    build: ./Job\ Service
    ports:
      - "3002:3000"
    depends_on:
      - job-db
    environment:
      DATABASE_URL: postgres://job_admin:job_password@job-db:5432/job_db

  # --- APPLICATION SERVICE stack ---
  app-service:
    build: ./Application\ Service
    ports:
      - "3003:3000"
    # This service could share a DB or have its own!